//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AplicacionesEntities : DbContext
    {
        public AplicacionesEntities()
            : base("name=AplicacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etiquetas> Etiquetas { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
    
        public virtual ObjectResult<ObtenerAcumuladoGastos_Result1> ObtenerAcumuladoGastos(string agrupacion)
        {
            var agrupacionParameter = agrupacion != null ?
                new ObjectParameter("agrupacion", agrupacion) :
                new ObjectParameter("agrupacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerAcumuladoGastos_Result1>("ObtenerAcumuladoGastos", agrupacionParameter);
        }
    }
}
