//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    
    public partial class ObtenerAcumuladoGastos_Result1
    {
        public Nullable<int> intervalo { get; set; }
        public string descorta { get; set; }
        public Nullable<double> importe { get; set; }
    }
}
